import json

notebook = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Misata Enterprise Data Generation (Deep Eval)\n",
    "\n",
    "This notebook evaluates the outputs of the 30,000+ row B2B SaaS synthetic dataset generated by `misata`, analyzing the effectiveness of the LLM constraints applied via prompt (Noise Injection, Curve Engines, and Correlated Dependencies)."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "plt.style.use('dark_background')\n",
    "sns.set_palette(\"coolwarm\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 1. Relational Map\n",
    "Load the massive datasets generated by the vectorized FactEngine."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "tenants = pd.read_csv('./deep_outputs/tenants.csv')\n",
    "subscriptions = pd.read_csv('./deep_outputs/subscriptions.csv')\n",
    "tickets = pd.read_csv('./deep_outputs/support_tickets.csv')\n",
    "\n",
    "print(f\"Tenants: {len(tenants)} Rows\")\n",
    "print(f\"Subscriptions: {len(subscriptions)} Rows\")\n",
    "print(f\"Support Tickets: {len(tickets)} Rows\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 2. Text Realism & Correlated Entities\n",
    "Let's check if the generic string generation hallucinated realistic B2B constraints, specifically if MRR ranges intelligently map to `plan_type`."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "display(tenants.head(5))\n",
    "\n",
    "merged = subscriptions.merge(tenants, left_on='tenant_id', right_on='id', suffixes=('', '_tenant'))\n",
    "print(\"MRR Profile by Plan Type:\")\n",
    "display(merged.groupby('plan_type')['amount'].agg(['mean', 'median', 'std', 'count']))\n",
    "\n",
    "plt.figure(figsize=(10,6))\n",
    "sns.violinplot(data=merged, x='plan_type', y='amount', inner=\"quartile\")\n",
    "plt.title('Subscription Cost (MRR) Correlated to Plan Type')\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 3. Black Friday Seasonality Constraints (Time Curves)\n",
    "The prompt asked for dramatic ticket peaks in January/February, and ZERO tickets on the weekends."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "date_cols = [c for c in tickets.columns if 'date' in c.lower() or 'created' in c.lower()]\n",
    "date_col = date_cols[0]\n",
    "\n",
    "tickets[date_col] = pd.to_datetime(tickets[date_col], errors='coerce')\n",
    "tickets_clean = tickets.dropna(subset=[date_col])\n",
    "\n",
    "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "# Monthly Profile\n",
    "monthly = tickets_clean.groupby(tickets_clean[date_col].dt.month).size()\n",
    "monthly.plot(kind='bar', ax=ax1, color='#FF5733')\n",
    "ax1.set_title('Tickets By Month (Peak Jan/Feb Expected)')\n",
    "ax1.set_xlabel('Month (1-12)')\n",
    "ax1.set_ylabel('Ticket Volume')\n",
    "\n",
    "# Weekend Profile\n",
    "weekly = tickets_clean.groupby(tickets_clean[date_col].dt.dayofweek).size()\n",
    "days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']\n",
    "ax2.bar(range(7), [weekly.get(i, 0) for i in range(7)], color='#33B5FF')\n",
    "ax2.set_xticks(range(7))\n",
    "ax2.set_xticklabels(days)\n",
    "ax2.set_title('Tickets By Day of Week (0 on weekends expected)')\n",
    "ax2.set_ylabel('Ticket Volume')\n",
    "\n",
    "plt.tight_layout()\n",
    "plt.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## 4. Analytics Safe Noise Imputation\n",
    "The prompt requested 8% null values simulating bad customer service agent logging."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "null_counts = tickets.isnull().sum()\n",
    "null_pct = (null_counts / len(tickets)) * 100\n",
    "\n",
    "summary = pd.DataFrame({'Total Nulls': null_counts, 'Percentage': null_pct})\n",
    "display(summary[summary['Total Nulls'] > 0])\n",
    "\n",
    "print(f\"\\nTotal Primary Key Orphans Found: {tickets['tenant_id'].isnull().sum()}\")\n",
    "print(\"(Should be 0 safely protecting the FK relationships!)\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open("Misata_EDA_Report.ipynb", "w") as f:
    json.dump(notebook, f, indent=1)
    
print("Successfully generated Misata_EDA_Report.ipynb")
