"""
Document generation for Misata.

Render any generated DataFrame as real documents — HTML, PDF, Markdown,
or plain text — using Jinja2 templates.  Works with both built-in templates
(``"invoice"``, ``"patient_report"``, etc.) and custom template strings or files.

Quickstart::

    import misata

    tables = misata.generate("An ecommerce store with 200 orders")

    # Built-in template — no template file needed
    paths = misata.generate_documents(
        tables, template="invoice",
        table="orders", output_dir="/tmp/invoices"
    )
    print(f"Generated {len(paths)} invoices")

    # Custom Jinja2 template string
    html = \"\"\"
    <html><body>
      <h1>Order #{{ order_id }}</h1>
      <p>Customer: {{ customer_id }} — Amount: ${{ amount }}</p>
    </body></html>
    \"\"\"
    paths = misata.generate_documents(
        tables, template=html,
        table="orders", output_dir="/tmp/custom"
    )

    # Auto-detect a sensible template from column names
    paths = misata.generate_documents(
        tables, template="auto",
        table="orders", output_dir="/tmp/auto"
    )

PDF output requires the optional ``weasyprint`` package::

    pip install misata[documents]
"""

from __future__ import annotations

import os
import re
from pathlib import Path
from typing import Any, Dict, List, Literal, Optional, Union


# ---------------------------------------------------------------------------
# Built-in HTML templates
# ---------------------------------------------------------------------------

_BASE_CSS = """
  body { font-family: 'Segoe UI', Arial, sans-serif; font-size: 14px;
         color: #1a1a1a; margin: 0; padding: 0; background: #f5f5f5; }
  .card { max-width: 740px; margin: 32px auto; background: #fff;
          border-radius: 8px; box-shadow: 0 2px 12px rgba(0,0,0,.08);
          overflow: hidden; }
  .header { padding: 28px 36px 20px; border-bottom: 3px solid var(--accent); }
  .header h1 { margin: 0 0 4px; font-size: 22px; color: var(--accent); }
  .header .sub { color: #666; font-size: 13px; }
  .body  { padding: 28px 36px; }
  .grid  { display: grid; grid-template-columns: 1fr 1fr; gap: 18px 32px; }
  .field { border-bottom: 1px solid #eee; padding-bottom: 10px; }
  .field .label { font-size: 11px; font-weight: 600; text-transform: uppercase;
                  letter-spacing: .5px; color: #888; margin-bottom: 3px; }
  .field .value { font-size: 14px; color: #111; }
  .highlight { background: #f8f9ff; border-left: 3px solid var(--accent);
               padding: 10px 14px; border-radius: 0 4px 4px 0; margin: 16px 0; }
  .footer { padding: 16px 36px; background: #fafafa;
            border-top: 1px solid #eee; font-size: 11px; color: #aaa;
            text-align: right; }
  .badge { display: inline-block; padding: 3px 10px; border-radius: 12px;
           font-size: 11px; font-weight: 600; background: var(--accent-light);
           color: var(--accent); }
  table.items { width: 100%; border-collapse: collapse; margin-top: 12px; }
  table.items th { background: var(--accent); color: #fff; padding: 8px 12px;
                   text-align: left; font-size: 12px; }
  table.items td { padding: 8px 12px; border-bottom: 1px solid #eee; }
  table.items tr:last-child td { border-bottom: none; }
  .total-row td { font-weight: 700; border-top: 2px solid var(--accent) !important; }
"""

_BUILTIN_TEMPLATES: Dict[str, str] = {

# ── Invoice ──────────────────────────────────────────────────────────────────
"invoice": """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Invoice</title>
<style>
  :root { --accent: #2563eb; --accent-light: #eff6ff; }
""" + _BASE_CSS + """
</style></head>
<body><div class="card">
  <div class="header">
    <h1>Invoice</h1>
    <div class="sub">
      {% if order_id %}#{{ order_id }}{% endif %}
      {% if placed_at %} &nbsp;·&nbsp; {{ placed_at }}{% endif %}
    </div>
  </div>
  <div class="body">
    <div class="grid">
      {% for key, val in _fields.items() %}
      <div class="field">
        <div class="label">{{ key | replace('_', ' ') | title }}</div>
        <div class="value">{{ val }}</div>
      </div>
      {% endfor %}
    </div>
    {% if amount %}
    <div class="highlight" style="margin-top:24px;">
      <div class="label">Total Amount</div>
      <div style="font-size:24px;font-weight:700;color:var(--accent);">
        ${{ "%.2f" | format(amount | float) }}
      </div>
    </div>
    {% endif %}
  </div>
  <div class="footer">Generated by Misata · synthetic data</div>
</div></body></html>""",

# ── Patient Report ────────────────────────────────────────────────────────────
"patient_report": """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Patient Report</title>
<style>
  :root { --accent: #059669; --accent-light: #ecfdf5; }
""" + _BASE_CSS + """
</style></head>
<body><div class="card">
  <div class="header">
    <h1>Patient Report</h1>
    <div class="sub">
      {% if patient_id %}ID: {{ patient_id }}{% endif %}
      {% if visit_date %} &nbsp;·&nbsp; {{ visit_date }}{% endif %}
    </div>
  </div>
  <div class="body">
    <div class="grid">
      {% for key, val in _fields.items() %}
      <div class="field">
        <div class="label">{{ key | replace('_', ' ') | title }}</div>
        <div class="value">{{ val }}</div>
      </div>
      {% endfor %}
    </div>
    {% if diagnosis or condition %}
    <div class="highlight">
      <div class="label">Clinical Notes</div>
      <div class="value">{{ diagnosis or condition }}</div>
    </div>
    {% endif %}
  </div>
  <div class="footer">Generated by Misata · synthetic data — not real medical information</div>
</div></body></html>""",

# ── User / Customer Profile ───────────────────────────────────────────────────
"user_profile": """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>User Profile</title>
<style>
  :root { --accent: #7c3aed; --accent-light: #f5f3ff; }
""" + _BASE_CSS + """
  .avatar { width: 56px; height: 56px; border-radius: 50%;
            background: var(--accent); color: #fff;
            display: flex; align-items: center; justify-content: center;
            font-size: 22px; font-weight: 700; margin-bottom: 12px; }
</style></head>
<body><div class="card">
  <div class="header" style="display:flex;align-items:center;gap:20px;">
    <div class="avatar">
      {{ (name or email or 'U')[0] | upper }}
    </div>
    <div>
      <h1>{{ name or email or 'User Profile' }}</h1>
      <div class="sub">
        {% if plan %}<span class="badge">{{ plan }}</span>{% endif %}
        {% if status %}&nbsp;<span class="badge">{{ status }}</span>{% endif %}
      </div>
    </div>
  </div>
  <div class="body">
    <div class="grid">
      {% for key, val in _fields.items() %}
      <div class="field">
        <div class="label">{{ key | replace('_', ' ') | title }}</div>
        <div class="value">{{ val }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="footer">Generated by Misata · synthetic data</div>
</div></body></html>""",

# ── Transaction Receipt ───────────────────────────────────────────────────────
"transaction_receipt": """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Transaction Receipt</title>
<style>
  :root { --accent: #d97706; --accent-light: #fffbeb; }
""" + _BASE_CSS + """
</style></head>
<body><div class="card">
  <div class="header">
    <h1>Transaction Receipt</h1>
    <div class="sub">
      {% if transaction_id %}Ref: {{ transaction_id }}{% endif %}
      {% if transaction_date %} &nbsp;·&nbsp; {{ transaction_date }}{% endif %}
    </div>
  </div>
  <div class="body">
    <div class="grid">
      {% for key, val in _fields.items() %}
      <div class="field">
        <div class="label">{{ key | replace('_', ' ') | title }}</div>
        <div class="value">{{ val }}</div>
      </div>
      {% endfor %}
    </div>
    {% if amount %}
    <div class="highlight" style="margin-top:24px;">
      <div class="label">Transaction Amount</div>
      <div style="font-size:22px;font-weight:700;color:var(--accent);">
        ${{ "%.2f" | format(amount | float) }}
      </div>
    </div>
    {% endif %}
  </div>
  <div class="footer">Generated by Misata · synthetic data</div>
</div></body></html>""",

# ── Generic Card ─────────────────────────────────────────────────────────────
"generic": """<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><title>Record</title>
<style>
  :root { --accent: #0ea5e9; --accent-light: #f0f9ff; }
""" + _BASE_CSS + """
</style></head>
<body><div class="card">
  <div class="header">
    <h1>{{ _title }}</h1>
    <div class="sub">{{ _subtitle }}</div>
  </div>
  <div class="body">
    <div class="grid">
      {% for key, val in _fields.items() %}
      <div class="field">
        <div class="label">{{ key | replace('_', ' ') | title }}</div>
        <div class="value">{{ val }}</div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="footer">Generated by Misata · synthetic data</div>
</div></body></html>""",
}

# Markdown equivalents — used when format="markdown"
_BUILTIN_MARKDOWN: Dict[str, str] = {
    "invoice": """\
# Invoice{% if order_id %} #{{ order_id }}{% endif %}

{% for key, val in _fields.items() %}- **{{ key | replace('_', ' ') | title }}**: {{ val }}
{% endfor %}
{% if amount %}**Total: ${{ "%.2f" | format(amount | float) }}**{% endif %}
""",
    "patient_report": """\
# Patient Report{% if patient_id %} – {{ patient_id }}{% endif %}

{% for key, val in _fields.items() %}- **{{ key | replace('_', ' ') | title }}**: {{ val }}
{% endfor %}{% if diagnosis %}
**Diagnosis**: {{ diagnosis }}{% endif %}
""",
    "generic": """\
# {{ _title }}

{% for key, val in _fields.items() %}- **{{ key | replace('_', ' ') | title }}**: {{ val }}
{% endfor %}
""",
}


# ── Auto-detect template from column names ────────────────────────────────────

_TEMPLATE_SIGNALS: List[tuple] = [
    # (template_name, columns that strongly suggest this template)
    ("invoice",             {"order_id", "amount", "placed_at", "invoice_id", "total"}),
    ("transaction_receipt", {"transaction_id", "transaction_date", "debit", "credit",
                             "account_id", "balance", "fraud_flag"}),
    ("patient_report",      {"patient_id", "diagnosis", "condition", "medication",
                             "visit_date", "disease", "treatment"}),
    ("user_profile",        {"user_id", "email", "plan", "status", "signup_date",
                             "subscription_id", "churned"}),
]


def _detect_template(columns: List[str]) -> str:
    col_set = {c.lower() for c in columns}
    best_name, best_score = "generic", 0
    for tname, signals in _TEMPLATE_SIGNALS:
        score = len(col_set & signals)
        if score > best_score:
            best_name, best_score = tname, score
    return best_name


# ---------------------------------------------------------------------------
# DocumentTemplate
# ---------------------------------------------------------------------------

class DocumentTemplate:
    """Jinja2-backed document template for generating per-row documents.

    Args:
        source: One of:
                - A built-in template name (``"invoice"``, ``"patient_report"``,
                  ``"user_profile"``, ``"transaction_receipt"``, ``"generic"``,
                  ``"auto"``)
                - A Jinja2 template string (HTML, Markdown, or plain text)
                - A path to a ``.html``, ``.md``, or ``.txt`` template file
        format: Output format (``"html"``, ``"markdown"``, ``"txt"``).
                Used only when ``source`` is a built-in name.

    Example::

        tmpl = misata.DocumentTemplate("invoice")
        html = tmpl.render({"order_id": "1234", "amount": 99.95})
    """

    def __init__(
        self,
        source: str,
        format: Literal["html", "markdown", "txt"] = "html",
    ):
        self.format = format
        self._source_label = source
        self._jinja_template = self._load(source, format)

    # ------------------------------------------------------------------
    def _load(self, source: str, fmt: str):
        try:
            import jinja2
        except ImportError as exc:
            raise ImportError(
                "Jinja2 is required for document generation. "
                "Install it with: pip install jinja2"
            ) from exc

        env = jinja2.Environment(autoescape=False, undefined=jinja2.Undefined)

        # Built-in name
        if source in _BUILTIN_TEMPLATES or source == "auto":
            if source == "auto":
                # Deferred — resolved at render time once columns are known
                return None
            if fmt == "markdown":
                tmpl_str = _BUILTIN_MARKDOWN.get(source, _BUILTIN_MARKDOWN["generic"])
            else:
                tmpl_str = _BUILTIN_TEMPLATES[source]
            return env.from_string(tmpl_str)

        # File path
        path = Path(source).expanduser()
        if path.exists():
            tmpl_str = path.read_text(encoding="utf-8")
            return env.from_string(tmpl_str)

        # Raw template string (contains template syntax or multi-line)
        return env.from_string(source)

    def _resolve_auto(self, columns: List[str], fmt: str):
        """Resolve the 'auto' template once column names are known."""
        import jinja2
        env = jinja2.Environment(autoescape=False, undefined=jinja2.Undefined)
        name = _detect_template(columns)
        if fmt == "markdown":
            return env.from_string(_BUILTIN_MARKDOWN.get(name, _BUILTIN_MARKDOWN["generic"]))
        return env.from_string(_BUILTIN_TEMPLATES[name])

    def render(self, row: Dict[str, Any], *, title: str = "Record", subtitle: str = "") -> str:
        """Render a single row dict into document content.

        Args:
            row:      Dict of column → value (one DataFrame row).
            title:    Used as ``{{ _title }}`` in generic templates.
            subtitle: Used as ``{{ _subtitle }}`` in generic templates.

        Returns:
            Rendered string (HTML, Markdown, or plain text).
        """
        jt = self._jinja_template
        if jt is None:
            # auto mode — resolve from row keys
            jt = self._resolve_auto(list(row.keys()), self.format)
            self._jinja_template = jt   # cache for subsequent rows

        # Build _fields: exclude common sentinel/id-noise columns from the grid
        _SKIP = {"_fields", "_title", "_subtitle"}
        fields = {k: v for k, v in row.items() if k not in _SKIP and v is not None}

        ctx: Dict[str, Any] = {
            "_fields": fields,
            "_title": title,
            "_subtitle": subtitle,
        }
        ctx.update({k: v for k, v in row.items()})  # expose all cols directly
        return jt.render(**ctx)


# ---------------------------------------------------------------------------
# generate_documents()
# ---------------------------------------------------------------------------

def generate_documents(
    tables: Dict[str, Any],
    template: Union[str, "DocumentTemplate"],
    *,
    table: Optional[str] = None,
    output_dir: str,
    format: Literal["html", "pdf", "markdown", "txt"] = "html",
    prefix: str = "doc",
    filename_col: Optional[str] = None,
    limit: Optional[int] = None,
) -> List[str]:
    """Generate one document per row from a Misata table.

    Args:
        tables:       ``{table_name: pd.DataFrame}`` dict from
                      :func:`~misata.generate` or :func:`~misata.generate_from_schema`.
        template:     Template to use.  Accepts:

                      - Built-in names: ``"invoice"``, ``"patient_report"``,
                        ``"user_profile"``, ``"transaction_receipt"``,
                        ``"generic"``, ``"auto"``
                      - A Jinja2 template string
                      - A :class:`DocumentTemplate` instance
                      - A path to a ``.html`` / ``.md`` / ``.txt`` file
        table:        Which table to use.  Defaults to the first table
                      in ``tables``.
        output_dir:   Directory to write documents into (created if absent).
        format:       Output format — ``"html"`` (default), ``"pdf"``,
                      ``"markdown"``, or ``"txt"``.  PDF requires
                      ``pip install weasyprint``.
        prefix:       Filename prefix (default ``"doc"``).
        filename_col: Column to use as the filename stem instead of a
                      numeric counter (e.g. ``"order_id"``).
        limit:        Cap on number of documents to generate.

    Returns:
        List of paths to generated files.

    Raises:
        ImportError: If ``format="pdf"`` and weasyprint is not installed.
        ValueError:  If the specified table is not found.

    Example::

        tables = misata.generate("A fintech company with 100 transactions")
        paths = misata.generate_documents(
            tables, "transaction_receipt",
            output_dir="/tmp/receipts",
            format="html",
        )
        print(paths[0])  # /tmp/receipts/doc_1.html
    """
    import pandas as pd

    # Resolve DataFrame
    if table is None:
        table = next(iter(tables))
    if table not in tables:
        raise ValueError(
            f"Table '{table}' not found. Available: {list(tables.keys())}"
        )
    df = tables[table]
    if limit is not None:
        df = df.head(limit)

    # Resolve template
    fmt_for_template = "markdown" if format == "markdown" else (
        "txt" if format == "txt" else "html"
    )
    if isinstance(template, DocumentTemplate):
        doc_tmpl = template
    else:
        doc_tmpl = DocumentTemplate(str(template), format=fmt_for_template)

    # Extension
    ext_map = {"html": ".html", "pdf": ".html", "markdown": ".md", "txt": ".txt"}
    ext = ext_map.get(format, ".html")

    out_path = Path(output_dir).expanduser()
    out_path.mkdir(parents=True, exist_ok=True)

    paths: List[str] = []
    for idx, (_, row) in enumerate(df.iterrows(), start=1):
        row_dict = {k: _safe_val(v) for k, v in row.items()}

        if filename_col and filename_col in row_dict:
            stem = str(row_dict[filename_col]).replace("/", "_").replace(" ", "_")
        else:
            stem = f"{prefix}_{idx}"

        content = doc_tmpl.render(row_dict, title=table.replace("_", " ").title())
        html_file = out_path / f"{stem}{ext}"
        html_file.write_text(content, encoding="utf-8")

        if format == "pdf":
            pdf_file = out_path / f"{stem}.pdf"
            _html_to_pdf(str(html_file), str(pdf_file))
            html_file.unlink(missing_ok=True)
            paths.append(str(pdf_file))
        else:
            paths.append(str(html_file))

    return paths


def _safe_val(v: Any) -> Any:
    """Return a JSON-safe scalar; convert NaN/NaT to None."""
    import math
    try:
        import pandas as pd
        if pd.isna(v):
            return None
    except Exception:
        pass
    if isinstance(v, float) and math.isnan(v):
        return None
    return v


def _html_to_pdf(html_path: str, pdf_path: str) -> None:
    try:
        from weasyprint import HTML  # type: ignore
    except ImportError as exc:
        raise ImportError(
            "PDF output requires weasyprint. "
            "Install with: pip install 'misata[documents]'"
        ) from exc
    HTML(filename=html_path).write_pdf(pdf_path)


# ---------------------------------------------------------------------------
# List built-ins
# ---------------------------------------------------------------------------

def list_document_templates() -> List[str]:
    """Return names of all built-in document templates.

    Example::

        misata.list_document_templates()
        # ['invoice', 'patient_report', 'transaction_receipt', 'user_profile', 'generic']
    """
    return sorted(_BUILTIN_TEMPLATES.keys())
