"""
LLM-powered schema generator using Groq Llama 3.3.

This module provides intelligent schema generation from natural language,
including:
- Reference tables with actual LLM-generated data (exercises, plans, meals)
- Transactional tables with foreign keys to reference tables
- Industry-realistic column configurations
"""

import json
import os
from pathlib import Path
from typing import Dict, List, Optional

from groq import Groq

from misata.curve_fitting import CurveFitter
from misata.feedback import FeedbackDatabase
from misata.schema import Column, OutcomeCurve, Relationship, ScenarioEvent, SchemaConfig, Table
from misata.research import DeepResearchAgent


# Load .env file if it exists
def _load_env():
    """Load environment variables from .env file."""
    env_paths = [
        Path.cwd() / ".env",
        Path.cwd().parent / ".env",  # apps/.env or api parent
        Path.cwd().parent.parent / ".env",  # Misata root from apps/api
        Path(__file__).parent.parent / ".env",  # packages/core/.env
        Path(__file__).parent.parent.parent / ".env",  # packages/.env
        Path(__file__).parent.parent.parent.parent / ".env",  # Misata root from packages/core/misata
        Path.home() / ".misata" / ".env",
    ]

    for env_path in env_paths:
        if env_path.exists():
            with open(env_path) as f:
                for line in f:
                    line = line.strip()
                    if line and not line.startswith("#") and "=" in line:
                        key, _, value = line.partition("=")
                        # Remove quotes if present
                        value = value.strip().strip("'\"")
                        os.environ.setdefault(key.strip(), value)
            break

_load_env()


SYSTEM_PROMPT = """You are Misata, an expert synthetic data architect. Your job is to generate REALISTIC database schemas based ONLY on the user's story. 

## CRITICAL: DO NOT USE DEFAULT EXAMPLES
- Generate tables that are SPECIFIC to the user's domain.
- If user says "pet store", create tables like "pets", "pet_categories", "pet_sales".
- If user says "music streaming", create tables like "songs", "artists", "streams".
- NEVER default to fitness/exercise/workout tables UNLESS the user explicitly asks for them.

## TABLE TYPES

### 1. REFERENCE TABLES (is_reference: true)
Small lookup tables (5-20 rows) with ACTUAL DATA you generate.
- MUST have an "id" column (integer, sequential from 1)
- Include realistic inline_data based on user's domain

### 2. TRANSACTIONAL TABLES (is_reference: false)
Large tables generated by code using foreign keys.
- Use row_count to specify size
- Use foreign_key type to reference parent tables

## OUTPUT FORMAT

{
  "name": "Dataset Name based on user's domain",
  "description": "Description of the domain",
  "seed": 42,
  "tables": [
    {
      "name": "domain_specific_reference_table",
      "is_reference": true,
      "inline_data": [
        {"id": 1, "name": "Value A", "price": 10.00},
        {"id": 2, "name": "Value B", "price": 20.00}
      ]
    },
    {
      "name": "domain_specific_transactional_table",
      "row_count": 10000,
      "is_reference": false
    }
  ],
  "columns": {
    "domain_specific_transactional_table": [
      {"name": "id", "type": "int", "distribution_params": {"distribution": "uniform", "min": 1, "max": 10000}, "unique": true},
      {"name": "ref_id", "type": "foreign_key", "distribution_params": {}},
      {"name": "amount", "type": "float", "distribution_params": {"distribution": "normal", "mean": 50, "std": 20}},
      {"name": "date", "type": "date", "distribution_params": {"start": "2024-01-01", "end": "2025-12-31"}}
    ]
  },
  "relationships": [
    {"parent_table": "domain_specific_reference_table", "child_table": "domain_specific_transactional_table", "parent_key": "id", "child_key": "ref_id"}
  ],
  "outcome_curves": [],
  "events": []
}

## SMART DEFAULTS FOR COLUMNS

Age: int, normal, mean: 35, std: 12, min: 18, max: 80
Price/Amount: float, exponential, scale: 50, min: 0.01, decimals: 2
Rating (1-5): int, categorical, choices: [1,2,3,4,5], probabilities: [0.05, 0.08, 0.15, 0.32, 0.40]
Quantity: int, poisson, lambda: 3, min: 1
Duration (min): int, normal, mean: 45, std: 20, min: 5
Boolean: boolean, probability: 0.5-0.9 depending on context
Date: date, start/end based on user's time context

## TEMPORAL PATTERNS & OUTCOME CURVES

If the user mentions ANY time-based patterns, EXTRACT them as outcome_curves:

If the user provides EXPLICIT numeric targets by period, you MUST output exact target curves:
- "50k in Jan, 80k in Feb, 120k in Mar" -> use `value_mode: "absolute"` and `target_value`
- "revenue rises from 50k in Jan to 200k in Dec" -> emit concrete monthly target_value points, not just relative values
- qualitative words like "dip in September" should become a lower target_value for September in the emitted monthly series
- If the user specifies sub-period patterns ("busy on weekdays", "spikes at month end"), set `intra_period_pattern` to one of: "weekday_heavy", "weekend_heavy", "start_heavy", "end_heavy". Default is "uniform".

Keywords to detect:
- "peak", "spike", "surge" -> High relative_value (0.8-1.0)
- "dip", "drop", "decline" -> Low relative_value (0.2-0.4)
- "growth", "upward trend" -> pattern_type: "growth"
- "seasonal", "monthly cycles" -> pattern_type: "seasonal"

Output format:
"outcome_curves": [
  {
    "table": "sales",
    "column": "amount",
    "time_column": "sale_date",
    "time_unit": "month",
    "pattern_type": "seasonal",
    "value_mode": "absolute",
    "intra_period_pattern": "weekday_heavy",
    "description": "High in December, low in February",
    "curve_points": [
      {"month": 1, "target_value": 50000},
      {"month": 9, "target_value": 90000},
      {"month": 12, "target_value": 200000}
    ]
  }
]

## NOISE CONFIGURATION
If the user mentions wanting messy, dirty, or imperfect data, include a `noise_config` object exactly like this:
"noise_config": {
  "mode": "analytics_safe",
  "null_rate": 0.05,
  "typo_rate": 0.02
}

## DATE RANGE RULES
- "Last 2 years" -> start: 2024-01-01, end: 2025-12-31
- "Past year" -> start: 2025-01-01, end: 2025-12-31
- "Historical data" -> start: 2020-01-01, end: 2025-12-31
- No mention -> Default to current year (2025)

Generate schemas ONLY based on the user's story. Be creative and domain-specific."""



GRAPH_REVERSE_PROMPT = """You are Misata, an expert at reverse-engineering data patterns.
Given a description of a desired chart or graph pattern, generate a schema that will
produce data matching that EXACT pattern when plotted.

Follow the same two-tier table structure:
- Reference tables with inline_data for lookup values
- Transactional tables with foreign keys for mass data

The user will describe a chart they want. Your job is to generate data that,
when plotted, produces that exact chart."""


ENRICH_SCHEMA_PROMPT = """You are Misata, an expert synthetic data architect. You receive a BARE database schema (table names, column names, types, relationships) and your job is to ENRICH it with realistic, mathematically intelligent data generation parameters.

## YOUR GOAL
Analyze the schema structure, infer the domain, and return enriched column definitions that will produce **realistic, correlated** synthetic data — not random noise.

## WHAT YOU MUST RETURN

For each column, return enriched `distribution_params` following these rules:

### 1. STATISTICAL DISTRIBUTIONS (pick the RIGHT one)
- Prices/amounts → `{"distribution": "exponential", "scale": 50, "min": 0.01, "decimals": 2}`
- Ratings (1-5) → `{"distribution": "categorical", "choices": [1,2,3,4,5], "probabilities": [0.05, 0.08, 0.15, 0.32, 0.40]}`
- Counts/quantities → `{"distribution": "poisson", "lambda": 3, "min": 1}`
- Ages → `{"distribution": "normal", "mean": 35, "std": 12, "min": 18, "max": 80}`
- Percentages → `{"distribution": "uniform", "min": 0, "max": 100, "decimals": 1}`
- Durations → `{"distribution": "normal", "mean": 45, "std": 20, "min": 5}`

### 2. CORRELATED COLUMNS (use `depends_on`)
When columns are logically related within the same table, use conditional distributions:
- Salary depends on job_title: `{"depends_on": "job_title", "mapping": {"Intern": {"mean": 40000, "std": 5000}, "CTO": {"mean": 200000, "std": 30000}}}`
- State depends on country: `{"depends_on": "country", "mapping": {"USA": ["CA", "TX", "NY"], "UK": ["England", "Scotland"]}}`
- Churn depends on plan: `{"depends_on": "plan_type", "mapping": {"free": 0.3, "pro": 0.1, "enterprise": 0.05}}`

### 3. TEXT TYPE INFERENCE (from column name)
- email, user_email → `{"text_type": "email"}`
- name, full_name, first_name, last_name → `{"text_type": "name"}`
- company, company_name, organization → `{"text_type": "company"}`
- phone, phone_number → `{"text_type": "phone"}`
- address, street → `{"text_type": "address"}`
- url, website, link → `{"text_type": "url"}`
- description, notes, comment → `{"text_type": "sentence"}`

### 4. CATEGORICAL COLUMNS (infer from domain)
- status columns → `{"choices": ["active", "inactive", "pending"], "probabilities": [0.7, 0.2, 0.1]}`
- priority → `{"choices": ["low", "medium", "high", "critical"], "probabilities": [0.2, 0.4, 0.3, 0.1]}`
- type/category → domain-specific choices with realistic probabilities

### 5. REFERENCE TABLES (small lookup tables)
If a table looks like a lookup (few expected rows, referenced by others via FK), convert it:
- Set `is_reference: true`
- Generate `inline_data` with realistic rows (5-20 rows)
- Include an `id` column with sequential integers

### 6. BUSINESS RULE CONSTRAINTS
Infer constraints from column names:
- hours/duration in timesheets → `{"name": "max_daily_hours", "type": "max_per_group", "group_by": ["employee_id", "date"], "column": "hours", "value": 8, "action": "cap"}`

## CRITICAL RULES
- Skip `foreign_key` columns entirely — return them unchanged
- Skip `id` columns that are primary keys — return them unchanged  
- Dates: provide appropriate `start` and `end` based on the inferred domain
- Every `int` and `float` column MUST have a `distribution` key in distribution_params
- Every `categorical` column MUST have `choices` and `probabilities`
- Every `text` column MUST have `text_type`
- Every `date` column MUST have `start` and `end`
- Be SPECIFIC to the domain you infer from the schema

## OUTPUT FORMAT

Return valid JSON with this structure:
{
  "inferred_domain": "Brief description of the domain",
  "columns": {
    "table_name": [
      {"name": "col_name", "type": "col_type", "distribution_params": {...}, "nullable": false, "unique": false}
    ]
  },
  "reference_tables": [
    {
      "name": "table_name",
      "inline_data": [{"id": 1, "name": "Value A"}, ...]
    }
  ],
  "constraints": {
    "table_name": [
      {"name": "rule_name", "type": "max_per_group", "group_by": [...], "column": "col", "value": 8, "action": "cap"}
    ]
  }
}"""


class LLMSchemaGenerator:
    """
    Generate realistic schemas from natural language using LLMs.

    Supports multiple providers:
    - groq: Groq Cloud (Llama 3.3) - Fast, free tier
    - openai: OpenAI (GPT-4o) - Best quality
    - ollama: Local Ollama - Free, private

    This is the "brain" of Misata - what makes it genuinely AI-powered.
    """

    # Provider configurations
    PROVIDERS = {
        "groq": {
            "base_url": None,  # Uses default
            "env_key": "GROQ_API_KEY",
            "default_model": "llama-3.3-70b-versatile",
        },
        "openai": {
            "base_url": None,
            "env_key": "OPENAI_API_KEY",
            "default_model": "gpt-4o-mini",
        },
        "ollama": {
            "base_url": "http://localhost:11434/v1",
            "env_key": None,  # No key needed for local
            "default_model": "llama3",
        },
    }

    def __init__(
        self,
        provider: Optional[str] = None,
        api_key: Optional[str] = None,
        model: Optional[str] = None,
        base_url: Optional[str] = None,
        enable_feedback: bool = False,
        feedback_db_path: Optional[str] = None,
        feedback_min_occurrences: int = 3,
    ):
        """
        Initialize the LLM generator.

        Args:
            provider: LLM provider ("groq", "openai", "ollama").
                      Defaults to MISATA_PROVIDER env var or "groq".
            api_key: API key. If not provided, reads from provider's env var.
            model: Model name. If not provided, uses provider default.
            base_url: Custom API base URL (for Ollama or compatible APIs).
        """
        # Determine provider
        self.provider = provider or os.environ.get("MISATA_PROVIDER", "groq").lower()
        self.enable_feedback = enable_feedback
        self.feedback_db_path = feedback_db_path
        self.feedback_min_occurrences = feedback_min_occurrences
        self._feedback_db: Optional[FeedbackDatabase] = None

        if self.provider not in self.PROVIDERS:
            raise ValueError(f"Unknown provider: {self.provider}. Use: {list(self.PROVIDERS.keys())}")

        config = self.PROVIDERS[self.provider]

        # Get API key
        self.api_key = api_key
        if not self.api_key and config["env_key"]:
            self.api_key = os.environ.get(config["env_key"])

        if not self.api_key and self.provider != "ollama":
            env_key = config["env_key"]
            raise ValueError(
                f"{self.provider.title()} API key required. "
                f"Set {env_key} environment variable or pass api_key parameter."
            )

        # Set model
        self.model = model or config["default_model"]

        # Set base URL
        self.base_url = base_url or config["base_url"]

        # Initialize client (all providers use OpenAI-compatible API)
        if self.provider == "groq":
            self.client = Groq(api_key=self.api_key)
        else:
            # OpenAI and Ollama use openai package
            try:
                from openai import OpenAI
            except ImportError:
                raise ImportError(
                    f"openai package required for {self.provider}. "
                    "Install with: pip install openai"
                )

            client_kwargs = {}
            if self.api_key:
                client_kwargs["api_key"] = self.api_key
            if self.base_url:
                client_kwargs["base_url"] = self.base_url

            # Ollama doesn't need a real API key
            if self.provider == "ollama":
                client_kwargs["api_key"] = "ollama"

            self.client = OpenAI(**client_kwargs)

    def _get_feedback_db(self) -> Optional[FeedbackDatabase]:
        """Lazily initialize the feedback database when feedback is enabled."""
        if not self.enable_feedback:
            return None
        if self._feedback_db is None:
            self._feedback_db = FeedbackDatabase(self.feedback_db_path)
        return self._feedback_db

    def _infer_feedback_industry(
        self,
        text: str = "",
        table_names: Optional[List[str]] = None,
    ) -> Optional[str]:
        """Infer a broad industry scope for feedback rules."""
        corpus = text.lower()
        if table_names:
            corpus = f"{corpus} {' '.join(table_names).lower()}"

        domain_keywords = {
            "saas": ["saas", "subscription", "billing", "mrr", "arr", "tenant"],
            "ecommerce": ["ecommerce", "order", "cart", "product", "shipping", "inventory"],
            "finance": ["finance", "payment", "account", "transaction", "bank"],
            "healthcare": ["health", "clinical", "patient", "diagnosis", "pharma", "procedure"],
            "education": ["student", "course", "lesson", "enrollment", "grade"],
        }

        for industry, keywords in domain_keywords.items():
            if any(keyword in corpus for keyword in keywords):
                return industry
        return None

    def _build_feedback_prompt(
        self,
        *,
        story: Optional[str] = None,
        schema: Optional[SchemaConfig] = None,
        prompt: Optional[str] = None,
    ) -> str:
        """Build an optional scoped feedback suffix for LLM prompts."""
        feedback_db = self._get_feedback_db()
        if feedback_db is None:
            return ""

        table_names = [table.name for table in schema.tables] if schema else None
        industry = self._infer_feedback_industry(
            text=" ".join(part for part in [story or "", prompt or ""] if part),
            table_names=table_names,
        )
        enhancement = feedback_db.generate_prompt_enhancement(
            min_occurrences=self.feedback_min_occurrences,
            industry=industry,
            table_names=table_names,
        )
        if not enhancement:
            return ""
        return f"\n\nLEARNED FEEDBACK RULES:\n{enhancement}"

    def generate_from_story(
        self,
        story: str,
        default_rows: int = 10000,
        temperature: float = 0.3,
    ) -> SchemaConfig:
        """
        Generate a realistic schema from a natural language story.

        Args:
            story: Natural language description of the data needs
            default_rows: Default row count if not specified in story
            temperature: LLM temperature (lower = more consistent)

        Returns:
            SchemaConfig ready for data generation
        """
        user_prompt = f"""Generate a complete synthetic data schema in JSON format for:

{story}

CRITICAL INSTRUCTIONS:
1. Generate tables SPECIFIC to the domain described above. DO NOT use generic fitness/exercise examples.
2. Create REFERENCE TABLES (is_reference: true) with inline_data for any lookup/configuration data relevant to THIS domain.
3. Create TRANSACTIONAL TABLES (is_reference: false) with row_count for high-volume data like users, transactions, events, etc.
4. Use foreign_key to link transactional tables to reference tables.
5. Default row count for transactional tables: {default_rows}
6. If the user mentions time patterns (peaks, dips, trends, growth), extract them as outcome_curves.
7. If the story contains explicit numeric targets by month/period, prefer exact `target_value` outcome_curves with `value_mode: "absolute"` over relative curves.
8. If the user mentions sub-period trends ("slow weekends"), set `intra_period_pattern` ("weekday_heavy", "weekend_heavy", "start_heavy", "end_heavy"). 
9. If the user mentions a time range (e.g., "last 2 years"), set date column start/end accordingly.

Output valid JSON. Be creative and domain-specific - DO NOT copy the system prompt examples."""
        user_prompt += self._build_feedback_prompt(story=story)


        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=temperature,
            max_tokens=6000,
            response_format={"type": "json_object"}
        )

        schema_dict = json.loads(response.choices[0].message.content)
        return self._parse_schema(schema_dict)

    def generate_from_graph(
        self,
        graph_description: str,
        temperature: float = 0.2,
    ) -> SchemaConfig:
        """
        REVERSE ENGINEERING: Generate schema that produces desired graph patterns.
        """
        user_prompt = f"""Generate a JSON schema that will produce this chart pattern:

{graph_description}

Include reference tables with inline_data for lookup values and transactional tables for mass data. Output valid JSON."""


        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": GRAPH_REVERSE_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=temperature,
            max_tokens=6000,
            response_format={"type": "json_object"}
        )

        schema_dict = json.loads(response.choices[0].message.content)
        return self._parse_schema(schema_dict)

    def _normalize_distribution_params(self, col_type: str, params: Dict) -> Dict:
        """Normalize LLM output variations in distribution_params."""
        normalized = params.copy()

        # Normalize date column parameters
        if col_type == "date":
            if "start_date" in normalized and "start" not in normalized:
                normalized["start"] = normalized.pop("start_date")
            if "end_date" in normalized and "end" not in normalized:
                normalized["end"] = normalized.pop("end_date")
            if "start" not in normalized:
                normalized["start"] = "2023-01-01"
            if "end" not in normalized:
                normalized["end"] = "2024-12-31"

        # Normalize categorical parameters
        if col_type == "categorical":
            if "options" in normalized and "choices" not in normalized:
                normalized["choices"] = normalized.pop("options")
            if "choices" not in normalized:
                normalized["choices"] = ["A", "B", "C"]

        # Curve Fitting for 'control_points'
        if "control_points" in normalized:
            try:
                points = normalized.pop("control_points")
                dist_type = normalized.get("distribution", "normal")
                fitter = CurveFitter()
                fitted_params = fitter.fit_distribution(points, dist_type)
                # Merge fitted params, keeping any manual overrides if they exist (or overwriting? let's overwrite for safety)
                normalized.update(fitted_params)
            except Exception:
                # If fitting fails, fallback to defaults or keep what we have
                pass

        return normalized

    def _parse_schema(self, schema_dict: Dict) -> SchemaConfig:
        """Parse LLM output into validated SchemaConfig."""

        # Parse tables
        tables = []
        for t in schema_dict.get("tables", []):
            is_ref = t.get("is_reference", False)
            inline = t.get("inline_data", None)
            row_count = t.get("row_count", len(inline) if inline else 100)

            tables.append(Table(
                name=t["name"],
                row_count=row_count,
                description=t.get("description"),
                is_reference=is_ref,
                inline_data=inline
            ))

        # Parse columns (only for transactional tables, reference tables use inline_data)
        columns = {}
        for table_name, cols in schema_dict.get("columns", {}).items():
            columns[table_name] = []
            for c in cols:
                col_type = c.get("type", "text")
                
                # Normalize LLM type variations to valid schema types
                type_mapping = {
                    "string": "text",
                    "str": "text",
                    "varchar": "text",
                    "char": "text",
                    "integer": "int",
                    "number": "float",
                    "decimal": "float",
                    "double": "float",
                    "timestamp": "datetime",
                    "bool": "boolean",
                    "enum": "categorical",
                    "category": "categorical",
                    "fk": "foreign_key",
                }
                col_type = type_mapping.get(col_type.lower(), col_type)
                
                raw_params = c.get("distribution_params", {})
                normalized_params = self._normalize_distribution_params(col_type, raw_params)

                columns[table_name].append(Column(
                    name=c["name"],
                    type=col_type,
                    distribution_params=normalized_params,
                    nullable=c.get("nullable", False),
                    unique=c.get("unique", False)
                ))

        # For reference tables without columns, create columns from inline_data
        for table in tables:
            if table.is_reference and table.inline_data and table.name not in columns:
                # Infer columns from first row of inline_data
                first_row = table.inline_data[0]
                columns[table.name] = []
                for col_name, value in first_row.items():
                    if isinstance(value, int):
                        col_type = "int"
                    elif isinstance(value, float):
                        col_type = "float"
                    else:
                        col_type = "text"
                    columns[table.name].append(Column(
                        name=col_name,
                        type=col_type,
                        distribution_params={}
                    ))

        # Parse relationships
        relationships = []
        for r in schema_dict.get("relationships", []):
            relationships.append(Relationship(
                parent_table=r["parent_table"],
                child_table=r["child_table"],
                parent_key=r["parent_key"],
                child_key=r["child_key"],
                temporal_constraint=r.get("temporal_constraint", False)
            ))

        # Parse events
        events = []
        for e in schema_dict.get("events", []):
            if not all(key in e for key in ["name", "table", "column", "condition", "modifier_type", "modifier_value"]):
                continue
            events.append(ScenarioEvent(
                name=e["name"],
                table=e["table"],
                column=e["column"],
                condition=e["condition"],
                modifier_type=e["modifier_type"],
                modifier_value=e["modifier_value"],
                description=e.get("description")
            ))

        # Parse outcome curves (temporal patterns from natural language)
        outcome_curves = []
        for c in schema_dict.get("outcome_curves", []):
            if not all(key in c for key in ["table", "column"]):
                continue
            outcome_curves.append(OutcomeCurve(
                table=c["table"],
                column=c["column"],
                time_column=c.get("time_column", "date"),
                time_unit=c.get("time_unit", "month"),
                pattern_type=c.get("pattern_type", "seasonal"),
                value_mode=c.get("value_mode", "auto"),
                intra_period_pattern=c.get("intra_period_pattern", "uniform"),
                description=c.get("description"),
                avg_transaction_value=c.get("avg_transaction_value"),
                min_transactions_per_period=c.get("min_transactions_per_period", 1),
                max_transactions_per_period=c.get("max_transactions_per_period", 10000),
                concentration=c.get("concentration", 2.0),
                start_date=c.get("start_date"),
                curve_points=c.get("curve_points", [])
            ))

        return SchemaConfig(
            name=schema_dict.get("name", "Generated Dataset"),
            description=schema_dict.get("description"),
            tables=tables,
            columns=columns,
            relationships=relationships,
            events=events,
            outcome_curves=outcome_curves,
            noise_config=schema_dict.get("noise_config"),
            seed=schema_dict.get("seed", 42)
        )

    def enrich_schema(
        self,
        schema: SchemaConfig,
        prompt: Optional[str] = None,
        temperature: float = 0.3,
    ) -> SchemaConfig:
        """
        Enrich a bare schema with LLM-inferred realistic distribution parameters.

        Takes a schema from introspection (SQLAlchemy, DB URL) that has only
        table/column structure and enriches it with:
        - Proper statistical distributions per column
        - Correlated column mappings (depends_on)
        - Reference table inline_data
        - Business rule constraints
        - Text type inference

        Args:
            schema: Bare SchemaConfig from introspection
            prompt: Optional user hint (e.g., "e-commerce with high churn")
            temperature: LLM temperature (lower = more consistent)

        Returns:
            Enriched SchemaConfig ready for realistic data generation
        """
        # Serialize schema to compact representation for the LLM
        schema_summary = self._serialize_schema_for_llm(schema)

        user_prompt = f"""Analyze this database schema and return enriched column definitions with realistic distribution parameters.

SCHEMA:
{json.dumps(schema_summary, indent=2)}

{f'DOMAIN HINT: {prompt}' if prompt else ''}

Return valid JSON with enriched columns, reference_tables, and constraints. Be domain-specific based on the table/column names you see."""
        user_prompt += self._build_feedback_prompt(schema=schema, prompt=prompt)

        response = self.client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": ENRICH_SCHEMA_PROMPT},
                {"role": "user", "content": user_prompt}
            ],
            temperature=temperature,
            max_tokens=8000,
            response_format={"type": "json_object"}
        )

        enrichment = json.loads(response.choices[0].message.content)
        return self._apply_enrichment(schema, enrichment)

    def _serialize_schema_for_llm(self, schema: SchemaConfig) -> Dict:
        """Serialize a SchemaConfig to a compact JSON for the LLM."""
        tables = []
        for t in schema.tables:
            tables.append({
                "name": t.name,
                "row_count": t.row_count,
                "is_reference": t.is_reference,
            })

        columns = {}
        for table_name, cols in schema.columns.items():
            columns[table_name] = []
            for c in cols:
                columns[table_name].append({
                    "name": c.name,
                    "type": c.type,
                    "nullable": c.nullable,
                    "unique": c.unique,
                })

        relationships = []
        for r in schema.relationships:
            relationships.append({
                "parent_table": r.parent_table,
                "child_table": r.child_table,
                "parent_key": r.parent_key,
                "child_key": r.child_key,
            })

        return {
            "tables": tables,
            "columns": columns,
            "relationships": relationships,
        }

    def _apply_enrichment(self, schema: SchemaConfig, enrichment: Dict) -> SchemaConfig:
        """
        Merge LLM enrichment back into the original SchemaConfig.

        Updates distribution_params, converts reference tables, adds constraints.
        Preserves all existing structure (table names, relationships, FK columns).
        """
        import copy
        enriched = copy.deepcopy(schema)

        # Type mapping for LLM output normalization
        type_mapping = {
            "string": "text", "str": "text", "varchar": "text", "char": "text",
            "integer": "int", "number": "float", "decimal": "float", "double": "float",
            "timestamp": "datetime", "bool": "boolean",
            "enum": "categorical", "category": "categorical", "fk": "foreign_key",
        }

        # 1. Update column distribution_params
        enriched_columns = enrichment.get("columns", {})
        for table_name, cols in enriched_columns.items():
            if table_name not in enriched.columns:
                continue

            # Build lookup of existing columns
            existing_cols = {c.name: c for c in enriched.columns[table_name]}

            for enriched_col_data in cols:
                col_name = enriched_col_data.get("name")
                if not col_name or col_name not in existing_cols:
                    continue

                existing_col = existing_cols[col_name]

                # Skip FK columns — they're handled by the simulator
                if existing_col.type == "foreign_key":
                    continue

                # Skip primary key id columns
                if col_name == "id" and existing_col.unique:
                    continue

                # Update distribution_params
                new_params = enriched_col_data.get("distribution_params", {})
                if new_params:
                    normalized = self._normalize_distribution_params(
                        existing_col.type, new_params
                    )
                    existing_col.distribution_params = normalized

                # Update type if LLM suggests a better one (e.g., text → categorical)
                new_type = enriched_col_data.get("type", existing_col.type)
                new_type = type_mapping.get(new_type.lower(), new_type)
                # Only allow safe type transitions
                safe_transitions = {
                    ("text", "categorical"),
                    ("int", "categorical"),
                    ("text", "boolean"),
                    ("int", "boolean"),
                }
                if new_type != existing_col.type:
                    if (existing_col.type, new_type) in safe_transitions:
                        existing_col.type = new_type

        # 2. Convert reference tables with inline_data
        ref_tables = enrichment.get("reference_tables", [])
        for ref in ref_tables:
            ref_name = ref.get("name")
            inline_data = ref.get("inline_data")
            if not ref_name or not inline_data:
                continue

            # Find the matching table
            for table in enriched.tables:
                if table.name == ref_name:
                    table.is_reference = True
                    table.inline_data = inline_data
                    table.row_count = len(inline_data)

                    # Update columns from inline_data if needed
                    if ref_name in enriched.columns:
                        first_row = inline_data[0]
                        new_cols = []
                        for col_name_key, value in first_row.items():
                            if isinstance(value, int):
                                col_type = "int"
                            elif isinstance(value, float):
                                col_type = "float"
                            elif isinstance(value, bool):
                                col_type = "boolean"
                            else:
                                col_type = "text"
                            new_cols.append(Column(
                                name=col_name_key,
                                type=col_type,
                                distribution_params={}
                            ))
                        enriched.columns[ref_name] = new_cols
                    break

        # 3. Add business rule constraints
        constraints_map = enrichment.get("constraints", {})
        for table_name, constraints_list in constraints_map.items():
            for table in enriched.tables:
                if table.name == table_name:
                    from misata.schema import Constraint
                    for c in constraints_list:
                        try:
                            constraint = Constraint(
                                name=c.get("name", "unnamed"),
                                type=c.get("type", "max_per_group"),
                                group_by=c.get("group_by", []),
                                column=c.get("column"),
                                value=c.get("value"),
                                action=c.get("action", "cap"),
                            )
                            table.constraints.append(constraint)
                        except Exception:
                            pass  # Skip invalid constraints
                    break

        return enriched


    def generate_from_story(self, story: str, use_research: bool = False, default_rows: int = 10000) -> SchemaConfig:
        """
        Generate schema from a user story.
        
        Args:
            story: The natural language description.
            use_research: If True, uses agent to find real companies for context.
            default_rows: Default row count for transactional tables.
        """
        context = ""
        if use_research:
            print("🕵️‍♂️ Deep Research Mode: ACTIVATED")
            # Simple heuristic to find likely domain
            domain = "SaaS"
            if "fitness" in story.lower(): domain = "Fitness App"
            elif "ecommerce" in story.lower() or "shop" in story.lower(): domain = "Ecommerce"
            elif "finance" in story.lower(): domain = "Fintech"
            
            try:
                # Use Mock Agent (fast)
                agent = DeepResearchAgent(use_mock=True) 
                entities = agent.search_entities(domain, "Competitors", limit=5)
                names = [e['name'] for e in entities]
                context = (
                    f"\n\nREAL WORLD CONTEXT (INJECTED):\n"
                    f"Research found these top players in {domain}: {', '.join(names)}.\n"
                    f"Use these names as examples in the 'inline_data' for reference tables if relevant."
                )
            except Exception as e:
                print(f"Research Agent Warning: {e}")

        # Construct the final prompt
        user_prompt = f"Story: {story}{context}\n\nDefault row count for transactional tables: {default_rows}\n\nGenerate the complete JSON schema."
        user_prompt += self._build_feedback_prompt(story=story)
        
        completion = self.client.chat.completions.create(
            messages=[
                {
                    "role": "system",
                    "content": SYSTEM_PROMPT,
                },
                {
                    "role": "user",
                    "content": user_prompt,
                }
            ],
            model=self.model,
            temperature=0.1,  # Low temp for JSON consistency
            response_format={"type": "json_object"},
        )

        response_content = completion.choices[0].message.content
        try:
            schema_dict = json.loads(response_content)
            return self._parse_schema(schema_dict)
        except json.JSONDecodeError:
            # Fallback text parsing if JSON mode fails (unlikely with Llama 3)
            # For now, just raise
            raise ValueError(f"Failed to generate valid JSON. Raw response: {response_content[:100]}...")

    def generate_from_graph(self, description: str) -> SchemaConfig:
        """Reverse engineer schema from graph description."""
        # Similar to above but uses GRAPH_REVERSE_PROMPT
        # For brevity, implementing basic pass-through
        return self.generate_from_story(description)

# Convenience functions
def generate_schema(story: str, api_key: Optional[str] = None, use_research: bool = False) -> SchemaConfig:
    """Quick helper to generate schema from story."""
    generator = LLMSchemaGenerator(api_key=api_key)
    return generator.generate_from_story(story, use_research=use_research)


def generate_from_chart(description: str, api_key: Optional[str] = None) -> SchemaConfig:
    """Quick helper to reverse-engineer schema from chart description."""
    generator = LLMSchemaGenerator(api_key=api_key)
    return generator.generate_from_graph(description)
