"""More row profiles for the free-text grammars in ``misata.textkit``.

Each list extends the profile list of the same name there. The entries are
written for this library; none is copied from a dataset.
"""

# (diagnosis, symptoms, meds as (name, dose), exam findings, plan lines,
#  patient advice, red flags, tests)
CASES = [
    ("sinusitis", ["facial pain", "a blocked nose", "pressure behind the eyes", "thick nasal discharge"],
     [("saline nasal rinse", "250ml"), ("mometasone nasal spray", "50mcg"), ("phenoxymethylpenicillin", "500mg")],
     ["tender over the maxillary sinuses", "nasal mucosa swollen, purulent discharge"],
     ["symptoms under 10 days, no antibiotics", "back-up prescription if no better in 7 days"],
     ["rinse your nose with salt water twice a day", "use a warm compress over your cheeks", "sleep with your head raised"],
     ["swelling around the eye", "a severe headache with a stiff neck"], ["observations"]),
    ("biliary colic", ["upper right abdominal pain", "pain after fatty meals", "nausea", "back pain under the shoulder blade"],
     [("paracetamol", "1g"), ("diclofenac", "50mg"), ("buscopan", "10mg")],
     ["tender right upper quadrant, Murphy's negative", "abdomen soft, no jaundice"],
     ["ultrasound shows gallstones, no cholecystitis", "routine surgical referral"],
     ["eat smaller, lower-fat meals", "keep a note of which foods set the pain off", "take pain relief as soon as an attack starts"],
     ["yellowing of the skin or eyes", "a fever with the pain"], ["abdominal ultrasound", "LFTs", "amylase"]),
    ("pulled hamstring", ["pain at the back of the thigh", "bruising on the thigh", "pain when walking"],
     [("ibuprofen", "400mg"), ("paracetamol", "1g")],
     ["tender proximal hamstring, bruising, power 4/5", "pain on resisted knee flexion"],
     ["grade 2 strain, physio referral", "graded return to sport over 4-6 weeks"],
     ["ice the back of the thigh for 20 minutes every few hours", "walk short distances rather than resting completely", "start gentle stretches once the pain eases"],
     ["sudden swelling of the whole leg", "numbness in the foot"], ["observations"]),
    ("pityriasis rosea", ["a scaly rash on the trunk", "a single larger patch first", "mild itching"],
     [("emollient", "500g"), ("cetirizine", "10mg")],
     ["oval scaly plaques along skin lines, herald patch on the back", "Christmas-tree distribution on the trunk"],
     ["reassured, self-limiting over 6-12 weeks", "no treatment needed beyond emollient"],
     ["use a plain moisturiser", "avoid perfumed soaps", "the rash can take up to three months to fade"],
     ["the rash becomes painful or blistered", "you are pregnant"], ["observations"]),
    ("nosebleed", ["bleeding from the nose", "blood in the throat", "repeated nosebleeds"],
     [("Naseptin cream", "15g"), ("tranexamic acid", "1g")],
     ["bleeding point on the left Little's area", "no active bleeding after pressure"],
     ["silver nitrate cautery", "anterior pack not needed"],
     ["pinch the soft part of your nose for 10 to 15 minutes", "lean forward, not back", "avoid blowing your nose for a week"],
     ["bleeding that won't stop after 20 minutes", "feeling faint"], ["FBC", "clotting screen"]),
    ("head lice", ["an itchy scalp", "lice seen in the hair", "a rash on the neck"],
     [("dimeticone lotion", "4%")],
     ["live lice and eggs on the scalp", "excoriations at the nape"],
     ["dimeticone, repeat in 7 days", "check household contacts"],
     ["comb wet hair with a detection comb every few days", "treat everyone in the house who has lice on the same day", "there is no need to keep your child off school"],
     ["broken, infected skin on the scalp", "a rash spreading beyond the neck"], ["observations"]),
    ("dehydration", ["dizziness", "a dry mouth", "passing little urine", "tiredness"],
     [("Dioralyte", "1 sachet"), ("paracetamol", "1g")],
     ["dry mucous membranes, capillary refill 3 seconds", "postural drop of 20 mmHg"],
     ["IV fluids 1 litre, tolerating oral fluids", "U&Es improving"],
     ["sip water or rehydration drinks every few minutes", "avoid alcohol and caffeine until you feel well", "check your urine is pale yellow"],
     ["fainting", "not passing urine for 12 hours"], ["U&Es", "urine dip"]),
    ("tennis elbow", ["pain on the outside of the elbow", "a weak grip", "pain lifting a kettle"],
     [("ibuprofen gel", "5%"), ("paracetamol", "1g")],
     ["tender lateral epicondyle, pain on resisted wrist extension", "full elbow range"],
     ["epicondylitis brace, physio exercises", "steroid injection discussed, not given"],
     ["rest from the movements that hurt", "lift with your palm facing up", "do the forearm stretches on the sheet each day"],
     ["a hot, swollen elbow", "numbness in the hand"], ["observations"]),
    ("frozen shoulder", ["shoulder pain", "stiffness lifting the arm", "pain at night"],
     [("naproxen", "500mg"), ("paracetamol", "1g")],
     ["global restriction, external rotation worst affected", "painful arc absent"],
     ["physio referral, consider hydrodilatation", "X-ray to exclude arthritis"],
     ["keep the arm moving within the pain", "do the pendulum exercises three times a day", "use a hot pack before exercising"],
     ["a fever with the shoulder pain", "weakness in the hand"], ["shoulder X-ray"]),
    ("ingrown toenail", ["a painful big toe", "redness around the nail", "pus from the toe"],
     [("flucloxacillin", "500mg"), ("paracetamol", "1g")],
     ["erythema and granulation tissue at the lateral nail fold", "no cellulitis spreading up the foot"],
     ["partial nail avulsion with phenol under local", "podiatry follow-up"],
     ["soak the foot in warm salty water twice a day", "wear wide, open shoes", "cut toenails straight across"],
     ["redness spreading up the foot", "a fever"], ["observations"]),
    ("glandular fever", ["a sore throat", "swollen glands", "extreme tiredness", "fever"],
     [("paracetamol", "1g"), ("ibuprofen", "400mg")],
     ["enlarged tonsils, posterior cervical lymphadenopathy", "spleen not palpable"],
     ["Monospot positive", "no contact sport for 4 weeks"],
     ["rest and drink plenty of fluids", "avoid contact sport for at least four weeks", "expect the tiredness to last a few weeks"],
     ["sudden pain in the upper left abdomen", "trouble swallowing fluids"], ["Monospot", "FBC", "LFTs"]),
    ("haemorrhoids", ["bleeding after the toilet", "itching around the bottom", "a lump at the anus"],
     [("Anusol", "1 application"), ("lactulose", "15ml"), ("fybogel", "1 sachet")],
     ["external haemorrhoid, no thrombosis", "PR exam normal apart from piles"],
     ["fibre and fluids, topical treatment", "referral if bleeding persists after 6 weeks"],
     ["eat more fibre and drink plenty of water", "don't strain or sit on the toilet for long", "use moist wipes rather than dry paper"],
     ["heavy or dark bleeding", "weight loss or a change in bowel habit"], ["FBC"]),
    ("whiplash", ["neck pain after a car accident", "neck stiffness", "headache"],
     [("ibuprofen", "400mg"), ("paracetamol", "1g"), ("diazepam", "2mg")],
     ["paraspinal tenderness, no midline tenderness", "Canadian C-spine rule negative"],
     ["imaging not indicated", "advice to keep moving"],
     ["keep your neck moving gently", "use a warm compress on the sore muscles", "sleep on a firm, low pillow"],
     ["numbness or weakness in the arms", "loss of balance"], ["observations"]),
    ("scabies", ["an itchy rash at night", "itching between the fingers", "a rash on the wrists"],
     [("permethrin cream", "5%")],
     ["burrows in the finger webs, excoriated papules on the wrists", "papules around the waist"],
     ["permethrin for the whole household, repeat in 7 days", "wash bedding at 60 degrees"],
     ["apply the cream to the whole body, not just the itchy areas", "wash clothes and bedding at 60 degrees", "the itch can last for a few weeks after treatment"],
     ["crusted or weeping skin", "a fever"], ["observations"]),
    ("acute kidney injury", ["reduced urine output", "swollen ankles", "nausea", "tiredness"],
     [("sodium chloride 0.9%", "1L"), ("paracetamol", "1g")],
     ["euvolaemic, no bladder palpable", "mild peripheral oedema"],
     ["ramipril and metformin held, fluids, daily U&Es", "renal ultrasound normal"],
     ["drink regularly through the day", "don't restart the tablets we stopped until your GP says so", "avoid ibuprofen and similar painkillers"],
     ["passing very little urine", "breathlessness when lying flat"], ["U&Es", "renal ultrasound", "urine dip"]),
    ("hypoglycaemia", ["shakiness", "sweating", "confusion", "a low sugar reading"],
     [("glucose gel", "40%"), ("gliclazide", "40mg")],
     ["capillary glucose 2.8 on arrival, 6.4 after treatment", "alert, GCS 15 after glucose"],
     ["gliclazide reduced", "diabetes nurse follow-up"],
     ["carry glucose tablets with you", "eat a snack with starch after treating a low", "check your sugar before driving"],
     ["repeated lows", "being too drowsy to eat or drink"], ["HbA1c", "U&Es", "capillary glucose"]),
    ("pneumothorax", ["sudden breathlessness", "sharp chest pain on one side", "pain on breathing in"],
     [("paracetamol", "1g"), ("codeine", "30mg")],
     ["reduced breath sounds on the right, sats 95%", "trachea central"],
     ["small primary pneumothorax, managed conservatively", "repeat CXR in clinic in 2 weeks"],
     ["don't fly until the doctors confirm your lung is fully healed", "never scuba dive unless a specialist clears you", "stop smoking - it raises the chance of it happening again"],
     ["breathlessness getting worse", "chest pain spreading"], ["chest X-ray"]),
    ("anaphylaxis", ["throat swelling", "wheeze", "hives", "feeling faint"],
     [("adrenaline auto-injector", "300mcg"), ("cetirizine", "10mg"), ("prednisolone", "40mg")],
     ["urticaria, wheeze settled after IM adrenaline", "BP 118/70 after treatment"],
     ["observed for 12 hours, two auto-injectors prescribed", "allergy clinic referral"],
     ["carry both adrenaline pens with you at all times", "avoid the food that caused the reaction", "tell friends and colleagues how to use the pen"],
     ["any return of throat swelling or breathing trouble", "feeling faint again"], ["mast cell tryptase"]),
    ("diverticulitis", ["lower left abdominal pain", "fever", "a change in bowel habit"],
     [("co-amoxiclav", "625mg"), ("paracetamol", "1g")],
     ["tender left iliac fossa, no peritonism", "low-grade temperature"],
     ["oral antibiotics, clear fluids for 48 hours", "colonoscopy in 6 weeks"],
     ["stick to clear fluids for a day or two, then build up slowly", "drink plenty of water", "once settled, eat more fibre"],
     ["pain getting much worse", "blood in your stool"], ["CRP", "FBC", "CT abdomen"]),
    ("bronchiolitis", ["a cough", "fast breathing", "poor feeding", "a runny nose"],
     [("saline drops", "0.9%"), ("paracetamol", "120mg")],
     ["fine crackles bilaterally, mild recession, sats 95%", "feeding 60% of usual"],
     ["supportive care, feeding plan", "safety-net advice to parents"],
     ["offer smaller feeds more often", "use saline drops before feeds", "keep your baby away from smoke"],
     ["pauses in breathing", "fewer than half the usual wet nappies"], ["observations"]),
    ("febrile convulsion", ["a fit with a fever", "a high temperature", "drowsiness after the fit"],
     [("paracetamol", "240mg"), ("ibuprofen", "100mg")],
     ["alert and back to normal, no neck stiffness", "inflamed throat, likely viral"],
     ["simple febrile seizure, no further tests", "parents reassured, written advice given"],
     ["keep your child cool but not cold", "give fever medicine for comfort, not to prevent fits", "stay calm and time any fit"],
     ["a fit lasting more than 5 minutes", "a rash that doesn't fade under a glass"], ["observations"]),
    ("deep vein thrombosis", ["a swollen calf", "calf pain", "a warm, red leg"],
     [("apixaban", "10mg"), ("rivaroxaban", "15mg")],
     ["left calf 3cm larger than right, tender", "Wells score 2"],
     ["Doppler confirms popliteal DVT, anticoagulation for 3 months", "cancer screening questions answered"],
     ["take your blood thinner at the same times each day", "keep active and avoid sitting for long periods", "wear the stocking if it was given"],
     ["sudden breathlessness or chest pain", "coughing up blood"], ["D-dimer", "Doppler ultrasound", "FBC"]),
    ("hand, foot and mouth disease", ["mouth ulcers", "a rash on the hands and feet", "fever", "poor eating"],
     [("paracetamol", "120mg"), ("ibuprofen", "100mg")],
     ["vesicles on the palms and soles, ulcers on the tongue", "well hydrated"],
     ["viral, supportive care", "no need to exclude from nursery once well"],
     ["offer cool drinks and soft foods", "use paracetamol for the sore mouth", "wash hands often to stop it spreading"],
     ["signs of dehydration", "drowsiness or a stiff neck"], ["observations"]),
    ("plantar fasciitis", ["heel pain", "pain on the first steps in the morning", "pain after standing"],
     [("ibuprofen", "400mg"), ("ibuprofen gel", "5%")],
     ["tender medial calcaneal tubercle", "tight calf muscles"],
     ["stretching programme, heel cups", "podiatry if no better in 3 months"],
     ["stretch your calves and feet before getting out of bed", "wear cushioned, supportive shoes", "roll your foot over a cold bottle"],
     ["sudden severe pain after a pop", "numbness in the foot"], ["observations"]),
]

# (place, access lines, safe spots, quirks)
HOMES = [
    ("mews house", ["cobbled lane behind the high street", "the archway off {street}, second door on the left", "door with the brass fox knocker"],
     ["in the coal bunker", "behind the planter", "with the neighbour opposite"], ["vans can't fit under the arch", "it's a pedestrian lane, park on {street}"]),
    ("tower block", ["floor {k}, lifts on the left", "block B, the entrance facing the car park", "intercom {n}, then the stairwell by the bins"],
     ["with the concierge on the ground floor", "in the locker by the lifts", "outside flat {n}"], ["one lift is often out", "the intercom doesn't work after 9pm"]),
    ("narrowboat marina", ["pontoon C, berth {n}", "gate code {code4}, then down to the water", "the boat with the red tiller"],
     ["in the marina office", "in the wooden box on the jetty", "on the stern deck"], ["the gate locks at dusk", "phone on arrival, signal is patchy"]),
    ("gated community", ["give the guard house name {lname}", "gate code {code4}, house {n}", "third right after the fountain"],
     ["with security at the gate", "in the porch", "behind the side gate"], ["the guards need a name", "satnav drops you at the back gate"]),
    ("allotment site", ["plot {n}, past the water trough", "gate on {street}, padlock code {code4}", "the shed with the green roof"],
     ["inside the shed", "under the bench by the water butt", "with the site secretary at plot 1"], ["only open at weekends", "no vehicles past the gate"]),
    ("church hall", ["side entrance off {street}", "the door with the noticeboard", "ring the vestry bell"],
     ["with the caretaker", "in the kitchen hatch", "in the porch"], ["only staffed on {weekday} mornings", "a playgroup is on until noon"]),
    ("pub", ["side door by the beer garden", "ring the bell at the cellar hatch", "ask behind the bar"],
     ["behind the bar", "in the cellar", "with whoever's on shift"], ["deliveries before 11am only", "the car park is shared with the shop"]),
    ("vet surgery", ["staff entrance at the back", "reception, not the main waiting room", "door marked deliveries"],
     ["with reception", "in the staff room", "in the pharmacy cupboard"], ["closed between 1 and 2", "keep the door shut - animals"]),
    ("primary school", ["main office via the visitor gate", "buzz the office and wait", "entrance on {street}, not the playground"],
     ["with the school office", "with the caretaker", "in the staff room"], ["no deliveries during drop-off or pick-up", "sign in at the office"]),
    ("dental practice", ["reception on the first floor", "side door marked staff only", "the door next to the chemist"],
     ["with the receptionist", "in the decontamination room", "behind the front desk"], ["closed on {weekday}s", "deliver after 9am"]),
    ("hair salon", ["salon door, ring if locked", "back entrance via the alley", "ask for {fname} at the desk"],
     ["behind the reception desk", "in the back room", "with the salon manager"], ["closed on Mondays", "busy at lunchtime, please be patient"]),
    ("recording studio", ["unmarked black door, buzz {n}", "basement of the old print works", "ring before arriving, we may be recording"],
     ["in the lobby", "with the studio manager", "on the desk by the door"], ["no knocking during a session - text {phone}", "the red light means recording"]),
    ("bakery", ["through the shop, ask at the counter", "back door on the side lane, ring the bell", "the green door next to the bakery"],
     ["behind the counter", "in the flour store", "with whoever is baking"], ["open from 6am", "closed after 2pm"]),
    ("garden flat", ["side path to the left of the house", "gate code {code4}, then the door at the back", "through the side gate, past the bikes"],
     ["behind the bins", "in the garden shed", "on the bench by the back door"], ["the gate sticks, push hard", "the dog is friendly but loud"]),
    ("barn conversion", ["track off the main road, past the paddock", "the barn with the glass front", "through the five-bar gate, close it after you"],
     ["in the porch", "in the stable on the left", "inside the garage"], ["horses in the field by the track", "potholes on the drive"]),
    ("lighthouse cottage", ["follow the coast road to the end", "the white cottage below the lighthouse", "car park at the top, walk down the steps"],
     ["in the boot room", "behind the wall out of the wind", "with the visitor centre"], ["the road floods at high tide", "the steps are steep"]),
    ("co-working space", ["reception on the 2nd floor", "ask for {fname} at the front desk", "the building with the bike racks"],
     ["with the community manager", "in the mail room", "in locker {n}"], ["reception closes at 6pm", "use the side door after hours"]),
    ("sheltered housing", ["main entrance, warden's office on the right", "ring flat {n} and wait - residents need time", "the door with the ramp"],
     ["with the warden", "in the communal lounge", "outside flat {n}"], ["please wait - residents take a while to answer", "no deliveries after 8pm"]),
]

# (booking, specific reasons, asks)
BOOKINGS = [
    ("spa day", ["skin reaction after the last treatment", "the voucher expired before we could use it", "pregnancy - the treatments aren't suitable", "the pool is closed for repairs"],
     ["swap to a facial instead", "extend the voucher by three months", "refund the deposit"]),
    ("driving lesson", ["test date moved", "instructor is off sick", "car in for its MOT", "exam clash at college"],
     ["move it to {weekday} at {time}", "keep the block booking", "credit the hour"]),
    ("music lessons", ["teacher moved away", "child lost interest", "clash with football practice", "moving house"],
     ["refund the rest of the term", "pause until {month}", "switch to online lessons"]),
    ("boiler service", ["the boiler was replaced", "landlord booked their own engineer", "no one home that day", "the engineer couldn't find the house last time"],
     ["rebook for {date}", "cancel the annual plan", "send a morning slot"]),
    ("photography session", ["the baby arrived early", "the weather forecast is awful", "outfits haven't arrived", "one of us is ill"],
     ["move to the studio instead", "rebook for {month}", "keep the deposit as credit"]),
    ("theatre tickets", ["the understudy is on", "train strike that evening", "babysitter fell through", "the show moved to a matinee"],
     ["exchange for a later date", "refund to the card ending {last4}", "credit to my account"]),
    ("sailing course", ["forecast gales all week", "not enough people signed up", "broke my wrist", "work trip came up"],
     ["move me to the {month} course", "full refund please", "transfer to my brother"]),
    ("catering order", ["the event has been cut to {k}0 guests", "venue changed to one with its own kitchen", "client cancelled the launch", "the menu changed after tasting"],
     ["adjust the order instead of cancelling", "refund the deposit less the tasting fee", "move it to {date}"]),
    ("glamping pod", ["site flooded", "the hot tub is out of action", "the kids have chickenpox", "our car broke down"],
     ["move to the October half-term", "voucher for next year", "refund under the weather policy"]),
    ("vet appointment", ["the dog is better", "can't get time off work", "booked with the wrong vet", "moving practices"],
     ["send the next available slot", "cancel the vaccination reminder too", "keep the records on file"]),
]

# (product kind, features, integrations, roles, wins, pains)
PRODUCTS = [
    ("restaurant reservation system", ["the table planner", "deposit capture", "the waitlist", "the guest notes", "the online booking widget", "SMS reminders"],
     ["Square", "Google Business", "Instagram"], ["front-of-house manager", "host", "restaurant owner"],
     ["no-shows fell by a third", "tables turn faster", "regulars get greeted by name"],
     ["double-booked tables on Saturdays", "deposits not refunding", "reminders going to the wrong number"]),
    ("construction project tool", ["the snagging list", "site diaries", "drawing versions", "the RFI tracker", "subcontractor portals", "the programme view"],
     ["Procore", "Dropbox", "Xero"], ["site manager", "quantity surveyor", "project engineer"],
     ["snag lists close weeks earlier", "nobody builds from an old drawing", "RFIs get answered in days"],
     ["photos missing from site diaries", "drawings syncing hours late", "the app crashing in low signal"]),
    ("veterinary practice software", ["appointment booking", "vaccine reminders", "clinical records", "the stock module", "insurance claims", "the client app"],
     ["Xero", "Petplan", "Stripe"], ["vet nurse", "practice manager", "receptionist"],
     ["vaccine uptake rose", "claims get paid sooner", "reminders run themselves"],
     ["duplicate pet records", "insurance claims bouncing", "reminders for pets that have died"]),
    ("gym management software", ["class booking", "membership billing", "door access", "the member app", "PT scheduling", "the attendance report"],
     ["GoCardless", "Mindbody", "Zapier"], ["gym manager", "personal trainer", "front desk"],
     ["fewer failed payments", "classes fill from the waitlist", "members book from the app"],
     ["door fobs not syncing", "failed direct debits not retried", "the app logging members out"]),
    ("logistics platform", ["shipment tracking", "label printing", "the carrier comparison", "returns handling", "proof of delivery", "the customs forms"],
     ["DHL", "Shopify", "Royal Mail"], ["warehouse lead", "shipping coordinator", "ops manager"],
     ["labels print in seconds", "customs forms fill themselves", "returns get processed the same day"],
     ["tracking stuck on dispatched", "labels printing at the wrong size", "customs codes rejected at the border"]),
    ("church management app", ["the giving page", "rota planning", "the member directory", "event sign-ups", "group messaging", "Gift Aid"],
     ["Stripe", "Mailchimp", "Planning Center"], ["church administrator", "pastor", "volunteer lead"],
     ["online giving doubled", "rotas fill without phone calls", "everyone knows what's on"],
     ["duplicate donors", "rota reminders sent twice", "Gift Aid exports failing"]),
    ("dental practice software", ["the appointment book", "treatment plans", "patient recalls", "online forms", "the X-ray viewer", "NHS claims"],
     ["Stripe", "Mailchimp", "Dentally"], ["dentist", "practice manager", "dental nurse"],
     ["recalls fill the diary", "forms are done before patients arrive", "claims go through first time"],
     ["X-rays not attaching", "recall texts going out twice", "the diary freezing at 8am"]),
    ("farm management software", ["herd records", "field mapping", "the spray log", "milk yield reports", "the medicine book", "subsidy forms"],
     ["John Deere", "Xero", "Cattle Tracing Service"], ["farm manager", "herdsman", "agronomist"],
     ["inspections take an hour, not a day", "spray records are always complete", "subsidy claims go in on time"],
     ["field maps not syncing offline", "duplicate animal IDs", "yield reports missing days"]),
]

CASES += [
    ("chest infection", ["a chesty cough", "green phlegm", "a temperature", "aching muscles"],
     [("amoxicillin", "500mg"), ("doxycycline", "100mg"), ("paracetamol", "1g")],
     ["coarse crackles at the left base, sats 96%", "chest crackles that clear on coughing"],
     ["5 days of antibiotics, review if not improving", "no admission needed, CRB-65 of 0"],
     ["drink plenty and rest while the fever settles", "sleep propped up on a few pillows", "a cough can hang on for three weeks after the infection"],
     ["chest pain when breathing", "coughing up blood"], ["chest X-ray", "CRP"]),
    ("urticaria", ["itchy welts", "a raised rash that moves around", "swollen eyelids"],
     [("fexofenadine", "180mg"), ("cetirizine", "10mg")],
     ["wheals on the arms and trunk, no angioedema of the tongue", "dermographism present"],
     ["daily antihistamine for 6 weeks", "trigger diary"],
     ["take the antihistamine every day, not only when the rash appears", "avoid very hot showers", "note down foods or medicines before each flare"],
     ["swelling of the tongue or throat", "difficulty breathing"], ["observations"]),
    ("gallstone pancreatitis", ["severe upper abdominal pain", "pain going through to the back", "vomiting"],
     [("morphine", "5mg"), ("ondansetron", "4mg")],
     ["epigastric tenderness and guarding, amylase raised", "mild jaundice"],
     ["admitted for fluids and analgesia, nil by mouth initially", "cholecystectomy planned on this admission"],
     ["avoid alcohol completely", "keep to low-fat meals until your operation", "come to every follow-up appointment"],
     ["the pain coming back", "yellowing of the skin"], ["amylase", "LFTs", "abdominal ultrasound"]),
    ("Bell's palsy", ["a drooping face on one side", "trouble closing one eye", "a change in taste"],
     [("prednisolone", "50mg"), ("lubricating eye drops", "0.2%")],
     ["lower motor neurone facial weakness, forehead involved", "no other neurology"],
     ["steroids within 72 hours", "eye protection advice, review in 3 weeks"],
     ["tape the eye shut at night if it won't close", "use the eye drops through the day", "most people recover fully within a few months"],
     ["weakness in an arm or leg", "a painful red eye"], ["observations"]),
    ("tonsillar abscess", ["a severe sore throat on one side", "trouble opening the mouth", "a muffled voice"],
     [("benzylpenicillin", "1.2g"), ("metronidazole", "400mg"), ("dexamethasone", "6.6mg")],
     ["uvula deviated to the left, bulging right peritonsillar area", "trismus"],
     ["needle aspiration by ENT", "IV antibiotics, step down to oral"],
     ["finish the antibiotics", "gargle with salt water", "keep sipping fluids even when it hurts"],
     ["drooling or trouble breathing", "the swelling returning"], ["FBC", "CRP"]),
    ("osteoarthritis flare", ["knee pain", "a stiff knee in the morning", "a swollen knee"],
     [("naproxen", "500mg"), ("capsaicin cream", "0.025%"), ("paracetamol", "1g")],
     ["crepitus, small effusion, no warmth", "reduced flexion to 100 degrees"],
     ["physio and weight advice", "steroid injection offered"],
     ["keep active - walking and swimming help", "use a stick in the opposite hand on bad days", "put ice on the knee after activity"],
     ["a hot, red, very swollen joint", "a fever"], ["knee X-ray"]),
    ("migraine with aura", ["zigzag lines in the vision", "a one-sided headache", "tingling in the hand"],
     [("sumatriptan", "50mg"), ("ibuprofen", "400mg")],
     ["neuro exam normal between attacks", "BP 124/78"],
     ["stop the combined pill", "headache diary, triptan at onset of headache"],
     ["take the triptan when the headache starts, not during the aura", "keep regular meals and sleep", "stop the combined pill and use another method"],
     ["an aura lasting over an hour", "weakness that doesn't go"], ["blood pressure"]),
    ("cystitis in pregnancy", ["stinging when passing urine", "needing to pass urine often", "lower tummy pain"],
     [("nitrofurantoin", "100mg"), ("cefalexin", "500mg")],
     ["suprapubic tenderness, urine dip positive", "no loin tenderness, afebrile"],
     ["7-day course, MSU sent", "test of cure after treatment"],
     ["drink plenty of water", "finish the full course", "bring a urine sample to your midwife after the course"],
     ["pain in your back or side", "contractions or bleeding"], ["urine culture"]),
    ("heat exhaustion", ["headache", "heavy sweating", "nausea", "cramps"],
     [("Dioralyte", "1 sachet"), ("paracetamol", "1g")],
     ["temp 37.9, tachycardic at 104, alert", "dry mucous membranes"],
     ["oral rehydration, cooling", "observed for 2 hours, improved"],
     ["stay in the shade and out of the midday heat", "drink water regularly even if not thirsty", "wear loose, light clothing"],
     ["confusion", "a temperature over 40C"], ["U&Es"]),
    ("ear wax impaction", ["muffled hearing", "a blocked ear", "ringing in the ear"],
     [("olive oil drops", "3 drops"), ("sodium bicarbonate drops", "5%")],
     ["right canal occluded with wax", "TM not visible"],
     ["drops for 2 weeks then irrigation", "hearing to be rechecked"],
     ["put the drops in three times a day for a fortnight", "lie with the ear up for five minutes after the drops", "don't use cotton buds"],
     ["ear pain or discharge", "sudden hearing loss"], ["observations"]),
    ("gout in the knee", ["a hot swollen knee", "severe knee pain", "unable to bend the knee"],
     [("colchicine", "500mcg"), ("prednisolone", "30mg")],
     ["warm effusion, aspirate shows urate crystals", "no fever, no wound"],
     ["colchicine and rest", "urate to be rechecked in 4 weeks"],
     ["rest the knee and keep it raised", "drink plenty of water", "cut down on alcohol, especially beer"],
     ["a fever with the swelling", "the swelling spreading"], ["joint aspirate", "serum urate"]),
    ("tooth abscess", ["toothache", "a swollen jaw", "a bad taste in the mouth"],
     [("amoxicillin", "500mg"), ("metronidazole", "400mg"), ("ibuprofen", "400mg")],
     ["swelling over the lower left molar, no trismus", "tender tooth, fluctuant gum"],
     ["antibiotics as a bridge to dental treatment", "see a dentist within 48 hours"],
     ["book an emergency dentist", "rinse with warm salt water", "take painkillers regularly, not just when it hurts"],
     ["swelling spreading to the eye or neck", "trouble swallowing or breathing"], ["observations"]),
]

HOMES += [
    ("tiny house", ["the cabin at the end of the farm track", "through the orchard, cabin on the right", "past the polytunnels"],
     ["in the log store", "on the decking", "in the green box by the steps"], ["satnav stops at the farmhouse, keep going", "the track is muddy in winter"]),
    ("loft apartment", ["the old warehouse, buzz {n}", "freight lift at the back, floor {k}", "steel door with the yellow sign"],
     ["with the building manager", "in the cage by the freight lift", "outside the loft door"], ["the freight lift needs a key", "the front buzzer is broken, call {phone}"]),
    ("cul-de-sac semi", ["last house in the close, red brick", "the semi with the camper van outside", "number {n}, blue garage door"],
     ["in the porch", "behind the side gate", "in the recycling box"], ["the doorbell plays a tune, it works", "the dog barks but can't get out"]),
    ("hotel", ["front desk, give the guest's name", "goods-in at the back on {street}", "the staff entrance by the car park"],
     ["with the concierge", "in the luggage room", "with the duty manager"], ["guest's name is {fname} {lname}, room {n}", "the front is a taxi rank - no stopping"]),
    ("retirement flat", ["block C, ring and wait for the warden", "ground floor, the door with the wreath", "the flat facing the garden"],
     ["with the warden", "inside the porch", "with the neighbour in flat {n}"], ["please give her time to answer", "no deliveries after 6pm"]),
    ("university lab", ["the chemistry building, goods-in", "room {n}, second floor, ask for {fname}", "delivery bay behind the library"],
     ["with stores", "in the goods-in cage", "with the lab manager"], ["closed at weekends", "hazard labels must face out"]),
    ("music venue", ["stage door on {street}", "ring the bell by the loading ramp", "the door under the fire escape"],
     ["with the box office", "behind the bar", "with the tour manager"], ["load-in from 2pm only", "nobody's in before noon"]),
    ("garden centre", ["goods-in at the back by the compost", "ask at the till", "the gate by the car park, then the barn"],
     ["in the goods-in shed", "with the till staff", "behind the counter"], ["busy on weekends, come early", "forklift working in the yard"]),
    ("fishing lodge", ["follow the river track past the weir", "the lodge with the boat outside", "gate by the bridge, code {code4}"],
     ["on the veranda", "in the boathouse", "with the warden at the hut"], ["no signal after the bridge", "the track floods after rain"]),
    ("police station", ["front counter, not the custody entrance", "the public entrance on {street}", "ring the intercom by the gate"],
     ["at the front counter", "with the station sergeant", "in the post room"], ["the front counter closes at 8pm", "no parking outside"]),
    ("youth hostel", ["reception, open 7am to 11pm", "the door by the bike shed", "the old mill building, ring for the warden"],
     ["at reception", "in the luggage room", "with the warden"], ["reception closes at 11pm", "the car park is tiny"]),
    ("dog groomer", ["the unit behind the pet shop", "side door, mind the dogs", "ask for {fname} at the counter"],
     ["behind the counter", "in the back room", "on the shelf by the door"], ["keep the door shut", "open {weekday} to Saturday"]),
]

BOOKINGS += [
    ("escape room", ["two of the group dropped out", "one of us is claustrophobic after all", "the birthday plan changed", "booked the horror room by mistake"],
     ["swap to the family room", "move to {weekday} night", "credit for a smaller group"]),
    ("kids' party venue", ["the birthday child has chickenpox", "half the class can't come", "we're doing it at home instead", "venue changed the theme"],
     ["move it to {date}", "refund the deposit", "swap to the smaller room"]),
    ("ferry crossing", ["the crossing was cancelled for weather", "car failed its MOT", "holiday cancelled", "booked the wrong port"],
     ["move to the next sailing", "refund the vehicle fare", "change the port to {city}"]),
    ("airport parking", ["flight cancelled", "a friend is dropping us off", "booked the wrong terminal", "dates changed"],
     ["refund the booking", "move to {date}", "change to the meet-and-greet option"]),
    ("guided tour", ["tour language isn't English", "the meeting point is too far", "weather alert for the area", "illness in the family"],
     ["switch to the afternoon tour", "voucher for later in the year", "refund to the card ending {last4}"]),
    ("hot air balloon flight", ["cancelled twice for wind", "the passenger is now pregnant", "moved away from the area", "the voucher expires soon"],
     ["extend the voucher", "refund under the weather policy", "transfer to {fname}"]),
]

PRODUCTS += [
    ("community app", ["the event calendar", "member chat", "the forum", "push notifications", "the moderation queue", "member profiles"],
     ["Discord", "Slack", "Stripe"], ["community manager", "moderator", "organiser"],
     ["event turnout went up", "moderation takes minutes", "members actually reply"],
     ["notifications arriving hours late", "spam getting past moderation", "chat history disappearing"]),
    ("survey tool", ["the question builder", "skip logic", "the results dashboard", "panel sourcing", "exports to SPSS", "the email invites"],
     ["Qualtrics", "Google Sheets", "Slack"], ["researcher", "insights manager", "marketing analyst"],
     ["surveys build in an hour", "response rates went up", "results go straight into decks"],
     ["skip logic breaking on mobile", "exports with scrambled columns", "invites landing in spam"]),
    ("travel booking tool", ["the trip planner", "the expense sync", "the approval flow", "rail booking", "the duty-of-care map", "hotel search"],
     ["Concur", "Outlook", "Slack"], ["travel manager", "executive assistant", "finance controller"],
     ["trips are approved in a day", "travel spend dropped", "we know where everyone is"],
     ["bookings missing from the calendar", "hotel rates higher than direct", "rail tickets not issuing"]),
    ("hotel PMS", ["the room rack", "channel management", "housekeeping lists", "the guest folio", "online check-in", "rate plans"],
     ["Booking.com", "Expedia", "Stripe"], ["front office manager", "revenue manager", "housekeeper"],
     ["overbookings stopped", "check-in takes two minutes", "rates update everywhere at once"],
     ["rooms double-sold on Booking.com", "folios splitting wrongly", "housekeeping lists not updating"]),
]

BOOKINGS += [
    ("tattoo appointment", ["the design isn't finished", "started antibiotics", "artist moved studios", "got cold feet about the placement"],
     ["move to the artist's next free day", "keep the deposit on file", "switch to a smaller piece"]),
    ("removal van", ["completion date slipped", "the buyer pulled out", "lift at the new block is broken", "decided to move ourselves"],
     ["move to {date}", "refund the deposit", "swap to a smaller van"]),
    ("golf tee time", ["course waterlogged", "partner pulled a back muscle", "work golf day clashes", "the club changed the format"],
     ["rebook for {weekday} at {time}", "credit to my membership", "move to the nine-hole course"]),
    ("language course", ["visa refused", "work schedule changed", "level test put me in the wrong class", "moving back home early"],
     ["transfer to the online class", "refund the remaining weeks", "defer to the {month} intake"]),
    ("nail appointment", ["broke a nail at work", "running late from the school run", "allergic reaction last time", "the technician is off"],
     ["rebook with {fname}", "any slot after {time}", "cancel without the fee please"]),
    ("dog kennels", ["the holiday fell through", "dog's vaccinations not up to date", "a neighbour can look after him", "the dog is unwell"],
     ["refund the deposit", "move to {month}", "keep the booking for the second week only"]),
]

HOMES += [
    ("castle gatehouse", ["the gatehouse at the bottom of the drive", "follow signs for the estate office", "through the arch, door on the right"],
     ["with the estate office", "in the porter's lodge", "in the box inside the arch"], ["the main gate shuts at 5pm", "visitors use the side entrance"]),
    ("chapel conversion", ["the old chapel with the round window", "door under the bell tower", "side gate beside the graveyard"],
     ["in the vestry porch", "behind the lych gate", "on the step under the arch"], ["the bell doesn't ring, knock loudly", "parking is on the lane"]),
    ("ski chalet", ["chalet {n}, top of the village road", "the wooden chalet past the lift station", "follow the piste-side path"],
     ["in the boot room", "with the chalet host", "in the ski locker"], ["snow chains needed after November", "deliveries only in the morning"]),
    ("motorhome pitch", ["pitch {n} at the {city} campsite", "the white motorhome by the shower block", "gate code {code4}, then left at the lake"],
     ["with the site reception", "in the box by the pitch post", "under the awning"], ["reception closes at 6pm", "we may be out walking - call {phone}"]),
    ("terraced cottage", ["the cottage with the green gate", "number {n}, end of the row", "the one with the bench outside"],
     ["in the porch", "behind the water butt", "with the neighbour at number {k}"], ["the lane is too narrow for big vans", "the doorbell is round the side"]),
    ("industrial estate unit", ["unit {n}, behind the tyre fitter", "the grey building with the blue shutter", "goods-in, gate 2"],
     ["with goods-in", "in the cage by the shutter", "at the trade counter"], ["closed between 12:30 and 1:30", "forklift in the yard - hi-vis please"]),
    ("houseshare", ["the blue door, flat {n} is upstairs", "ring the bell for room {k}", "the house with the bikes outside"],
     ["in the hallway", "on the shelf by the door", "with whoever answers"], ["write the name clearly - five of us live here", "the front door sticks"]),
    ("vineyard", ["follow the track between the vines", "the tasting room by the car park", "the winery building, not the house"],
     ["in the tasting room", "with the cellar staff", "in the barrel store"], ["harvest traffic in September", "closed on Mondays"]),
]

PRODUCTS += [
    ("subscription box platform", ["the box builder", "skip-a-month", "the referral scheme", "churn surveys", "the shipping calendar", "billing retries"],
     ["Shopify", "Stripe", "Klaviyo"], ["founder", "retention manager", "fulfilment lead"],
     ["fewer cancellations after we added skip", "referrals bring in new boxes", "billing retries rescue failed cards"],
     ["subscriptions renewing twice", "skip requests ignored", "cards retried on the wrong day"]),
    ("IT asset management tool", ["the asset register", "laptop provisioning", "licence tracking", "the offboarding checklist", "warranty alerts", "MDM sync"],
     ["Jamf", "Intune", "Okta"], ["IT manager", "service desk analyst", "CTO"],
     ["laptops ship ready on day one", "licences stopped going to waste", "offboarding is one click"],
     ["devices disappearing from the register", "the MDM sync failing nightly", "warranty alerts never sent"]),
    ("crowdfunding platform", ["the campaign page", "reward tiers", "backer updates", "pledge management", "the stretch goal tracker", "fulfilment surveys"],
     ["Stripe", "Mailchimp", "Shopify"], ["creator", "campaign manager", "community lead"],
     ["we hit our goal in a day", "backers get updates without us chasing", "surveys collect addresses cleanly"],
     ["pledges charged twice", "reward tiers vanishing", "survey links expiring early"]),
]

HOMES += [
    ("flat above the chippy", ["door to the right of the chip shop", "ring the top bell, the shop can't take it", "blue door, stairs straight up"],
     ["inside the stairwell door", "with the chippy if I'm out", "behind the bin store gate"], ["the shop opens at 4pm", "the bell rings twice, wait a moment"]),
    ("farm shop", ["the barn shop past the duck pond", "goods-in by the cold store", "the big green barn on the left"],
     ["with the shop till", "in the cold store if chilled", "on the pallet by the door"], ["closed on {weekday}s", "watch for the hens in the yard"]),
    ("canal-side flat", ["block by the lock gates, door 3", "towpath entrance, gate code {code4}", "the flats with the red balconies"],
     ["with the concierge", "in the bike store", "outside flat {n}"], ["no vans on the towpath", "the lift is key-fob only"]),
    ("new-build flat", ["block {k}, the one still with scaffolding", "the entrance facing the car park", "core B, floor {k}"],
     ["in the parcel lockers", "with the building manager", "outside the flat door"], ["postcode not on all satnavs yet", "the intercom isn't connected yet - call {phone}"]),
    ("gamekeeper's cottage", ["past the estate gates, first cottage", "the cottage by the pheasant pens", "follow the beech avenue to the end"],
     ["in the log store", "in the green box on the wall", "inside the porch"], ["dogs loose in the yard", "shoot days on Saturdays - come before 9"]),
    ("dental lab", ["unit 4, behind the opticians", "the door marked laboratory", "ring and wait - we may be casting"],
     ["with the lab manager", "on the goods-in shelf", "with reception upstairs"], ["closed at lunch", "temperature-sensitive - don't leave outside"]),
    ("charity shop", ["the shop on the corner of {street}", "donations door round the side", "ask at the till"],
     ["behind the till", "in the back room", "with the volunteer on duty"], ["volunteers change daily - name the parcel", "open 10 to 4"]),
    ("vicarage", ["the big house beside the church", "the drive opposite the war memorial", "side door by the study window"],
     ["in the porch", "with the church office", "behind the garden gate"], ["the vicar may be at a service", "the dog is old and harmless"]),
    ("student flat", ["flat {n}, the block behind the union", "ask at the halls desk for {fname}", "the third floor, door with the fairy lights"],
     ["at the halls reception", "outside the flat door", "in the common room"], ["reception is closed on Sundays", "names on the buzzer are out of date"]),
    ("lock-keeper's cottage", ["the cottage at the lock, down the slipway", "park at the top and walk down", "the gate by the weir"],
     ["in the boat shed", "on the bench by the door", "with the lock-keeper"], ["the slipway is steep", "no turning space for vans"]),
]
